Update README.md
GameLoop-it/faq-gamedev pull request #1
Opened 2020-12-18 18:18 UTC by davcri

2020-12-19 18:03 UTC, encelo requested changes
Qualche piccola correzione e suggerimento.

2020-12-19 18:03 UTC, encelo commented on README.md
> +Avere un portfolio aiuta a dimostrare le proprie competenze e attitudini
```suggestion
Avere un portfolio aiuta a dimostrare le proprie competenze ed attitudini
```

2020-12-19 18:03 UTC, encelo commented on README.md
> +Marco Palombo (Mediatonic, ex-Pixion Games) ha raccontato il suo intero percorso: da
```suggestion
Marco Colombo (Mediatonic, ex-Pixion Games) ha raccontato il suo intero percorso: da
```

2020-12-19 18:03 UTC, encelo commented on README.md
> +Per chi vuole approfondire gamplay programming, sicuramente un ottimo punto di inizio
```suggestion
Per chi vuole approfondire gameplay programming, sicuramente un ottimo punto di inizio
```

2020-12-20 10:19 UTC, davcri commented
Grazie per la review @encelo! Accetto e faccio merge.

2020-12-20 10:20 UTC, merged

2020-12-20 10:22 UTC, davcri commented
Ah cavolo pensavo i suggerimenti fossero già integrati nella PR, invece erano parte della review. Ho aggiornato ora il main con i fix.